definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  handlers.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  sqlc.Book:
    properties:
      author:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  sqlc.CreateBookParams:
    properties:
      author:
        type: string
      title:
        type: string
    type: object
  sqlc.CreateUserParams:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  sqlc.CreateUserRow:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  sqlc.UpdateBookParams:
    properties:
      author:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  description: This is the backend for TryCo.
  title: TryCo API
  version: "1.0"
paths:
  /api/v1/books:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/sqlc.Book'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: GetBooks
      tags:
      - books
    post:
      parameters:
      - description: Book object
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/sqlc.CreateBookParams'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sqlc.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      security:
      - SessionCookie: []
      summary: CreateBook
      tags:
      - books
  /api/v1/books/{id}:
    delete:
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      security:
      - SessionCookie: []
      summary: DeleteBook
      tags:
      - books
    get:
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sqlc.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: GetBook
      tags:
      - books
    put:
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Book object
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/sqlc.UpdateBookParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sqlc.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      security:
      - SessionCookie: []
      summary: UpdateBook
      tags:
      - books
  /api/v1/users:
    post:
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/sqlc.CreateUserParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sqlc.CreateUserRow'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create User
      tags:
      - users
  /api/v1/users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get User By ID
      tags:
      - users
securityDefinitions:
  SessionCookie:
    in: cookie
    name: _SESSION_ID
    type: apiKey
swagger: "2.0"
